layout_spectrum: 0.2956989
color:
  saturation: 0.546595
  lightness: 0.5734767
  brandStrength: 0.4784946
  brandColors:
    - '#EAEBE7'
    - '#201E16'
    - '#ABBD1F'
    - '#767666'
    - '#88280F'
  rhythmicContrast: 0.6935484
typography_spectrum: 0.9516129
name: Alimos
